@startuml

skinparam componentStyle uml2

database Mysql
database Neo4J
database "Elastic Search"

cloud "Kafka\nCLAIM_CREATE_DB"
cloud "Kafka\nCLAIM_CREATE_SEARCH"
cloud "Kafka\nTASK_CREATE"
cloud "Kafka\nLOCATION_CREATE"
cloud "Kafka\nCLAIM_CREATED"
cloud "Kafka\nTASK_CREATED"
cloud "Kafka\nGRAPH_CREATE"

actor User

User --> [Browser] : 0
[Browser] --> [Locations] : 1 search
[Locations] --> [post.ch] : 1.1 search
[Browser] --> [Claims] : 2 create
[Claims] --> [Tasks] : 2.1 validate
[Claims] --> [Kafka\nCLAIM_CREATE_DB] : 2.2
[Claims] --> [Kafka\nCLAIM_CREATE_SEARCH] : 2.3
[Claims] --> [Kafka\nTASK_CREATE] : 2.4
[Claims] --> [Kafka\nGRAPH_CREATE] : 2.5
[Claims] --> [Kafka\nLOCATION_CREATE] : 2.6

[Kafka\nCLAIM_CREATE_DB] --> [Claims] : 2.2.1
[Claims] --> [Mysql] : 2.2.1.1
[Claims] --> [Kafka\nCLAIM_CREATED] : 2.2.1.1.1
[Kafka\nCLAIM_CREATED] --> [Web] : 2.2.1.1.1.1
[Web] --> [Browser] : 2.2.1.1.1.1.1\nRefresh

[Kafka\nCLAIM_CREATE_SEARCH] --> [Claims] : 2.3.1
[Claims] --> [Elastic Search] : 2.3.1.1

[Kafka\nTASK_CREATE] --> [Tasks] : 2.4.1
[Tasks] --> [Mysql] : 2.4.1.1
[Tasks] --> [Kafka\nTASK_CREATED] : 2.4.1.1.1
[Kafka\nTASK_CREATED] --> [Web] : 2.4.1.1.1.1
[Web] --> [Browser] : 2.4.1.1.1.1.1\nRefresh

[Kafka\nGRAPH_CREATE] --> [Graphs] : 2.5.1
[Graphs] --> [Neo4J] : 2.5.1.1

[Kafka\nLOCATION_CREATE] --> [Locations] : 2.6.1
[Locations] --> [Graphs] : 2.6.1.1
[Graphs] --> [Neo4J] : 2.6.1.1.1

@enduml
