CREATE INDEX I_COMPONENTS_CONTRACT_ID ON T_COMPONENTS (CONTRACT_ID);
CREATE INDEX I_COMPONENTS_PARENT_ID ON T_COMPONENTS (PARENT_ID);

CREATE INDEX I_CONDITIONS_CONTRACT_ID ON T_CONDITIONS (CONTRACT_ID);
CREATE INDEX I_CONDITIONS_COMPONENT_ID ON T_CONDITIONS (COMPONENT_ID);
