CREATE TABLE T_CONDITIONS (
  ID               VARCHAR(36),
  COMPONENT_ID     VARCHAR(36),
  CONTRACT_ID      VARCHAR(36),
  CONDITION_ID     VARCHAR(36),
  PRIMARY KEY(ID)
)
;

-- fk to contracts
ALTER TABLE T_CONDITIONS
ADD CONSTRAINT FK_CONTRACT_ID
FOREIGN KEY (CONTRACT_ID) REFERENCES T_CONTRACTS(ID);

-- fk to components
ALTER TABLE T_CONDITIONS
ADD CONSTRAINT FK_CONDITIONS_COMPONENT_ID
FOREIGN KEY (COMPONENT_ID) REFERENCES T_COMPONENTS(ID);
