ALTER TABLE T_CONTRACTS2 ADD COLUMN OFFERED_AT timestamp(3);
ALTER TABLE T_CONTRACTS2 ADD COLUMN OFFERED_BY VARCHAR(50);

ALTER TABLE T_CONTRACTS2 ADD COLUMN ACCEPTED_AT timestamp(3);
ALTER TABLE T_CONTRACTS2 ADD COLUMN ACCEPTED_BY VARCHAR(50);

ALTER TABLE T_CONTRACTS2 ADD COLUMN APPROVED_AT timestamp(3);
ALTER TABLE T_CONTRACTS2 ADD COLUMN APPROVED_BY VARCHAR(50);
