CREATE TABLE T_PARTNERS (
  ID            VARCHAR(36),
  FIRST_NAME    VARCHAR(100)   NOT NULL,
  LAST_NAME     VARCHAR(100)   NOT NULL,
  TYPE          VARCHAR(20)    NOT NULL,
  DOB           DATE           NOT NULL,    -- date of birth / established
  EMAIL         VARCHAR(100),
  PHONE         VARCHAR(100),
  PRIMARY KEY(ID)
)
;

CREATE INDEX I_PARTNERS_FIRST_NAME ON T_PARTNERS (FIRST_NAME);
CREATE INDEX I_PARTNERS_LAST_NAME  ON T_PARTNERS (LAST_NAME);
CREATE INDEX I_PARTNERS_DOB        ON T_PARTNERS (DOB);
CREATE INDEX I_PARTNERS_EMAIL      ON T_PARTNERS (EMAIL);
CREATE INDEX I_PARTNERS_PHONE      ON T_PARTNERS (PHONE);

CREATE TABLE T_ADDRESSES (
  ID           VARCHAR(36),
  PARTNER_ID   VARCHAR(36)     NOT NULL,    -- id of parent
  STREET       VARCHAR(200)    NOT NULL,
  HOUSE_NUMBER VARCHAR(10)     NOT NULL,
  POSTCODE     VARCHAR(20)     NOT NULL,
  CITY         VARCHAR(100)    NOT NULL,
  STATE        VARCHAR(100)    NOT NULL,
  COUNTRY      VARCHAR(100)    NOT NULL,
  ADDRESS_TYPE VARCHAR(20)     NOT NULL,
  PRIMARY KEY(ID)
)
;

-- fk to partner
ALTER TABLE T_ADDRESSES
ADD CONSTRAINT FK_ADDRESSES_PARTNER_ID
FOREIGN KEY (PARTNER_ID) REFERENCES T_PARTNERS(ID);
