CREATE TABLE CONTRACTS
(
  ID VARCHAR(36),
  CONTRACTNUMBER VARCHAR(36) NOT NULL,
  VERSION INT NOT NULL,
  FROM_ DATETIME(3) NOT NULL,
  TO_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE CONTRACTS ADD INDEX (CONTRACTNUMBER);

CREATE TABLE CONTRACTS_AUD (
  ID VARCHAR(36) NOT NULL,
  CONTRACTNUMBER VARCHAR(36),
  VERSION INT,
  FROM_ DATETIME(3),
  TO_ DATETIME(3),

  REV BIGINT NOT NULL,
  REVTYPE TINYINT,
  PRIMARY KEY (ID, REV)
);

ALTER TABLE CONTRACTS_AUD
   ADD CONSTRAINT CONTRACTS_AUD_REVINFO
   FOREIGN KEY (REV)
   REFERENCES REVINFO(REV)
;
