CREATE TABLE PRODUCTS
(
  ID VARCHAR(36),
  CONTRACT_ID VARCHAR(36) NOT NULL,
  VERSION INT NOT NULL,
  FROM_ DATETIME(3) NOT NULL,
  TO_ DATETIME(3) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DISCOUNT DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE PRODUCTS
   ADD CONSTRAINT PRODUCTS_CONTRACTS
   FOREIGN KEY (CONTRACT_ID)
   REFERENCES CONTRACTS(ID)
;

CREATE TABLE PRODUCTS_AUD (
  ID VARCHAR(36) NOT NULL,
  CONTRACT_ID VARCHAR(36),
  VERSION INT,
  FROM_ DATETIME(3),
  TO_ DATETIME(3),
  DISCOUNT DECIMAL(3,1),
  NAME VARCHAR(50),

  REV BIGINT NOT NULL,
  REVTYPE TINYINT,
  PRIMARY KEY (ID, REV)
);

ALTER TABLE PRODUCTS_AUD
   ADD CONSTRAINT PRODUCTS_AUD_REVINFO
   FOREIGN KEY (REV)
   REFERENCES REVINFO(REV)
;

CREATE TABLE BUILDING_PRODUCTS
(
  ID VARCHAR(36),
  INDEX_VALUE DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE BUILDING_PRODUCTS
   ADD CONSTRAINT BUILDING_PRODUCTS_PRODUCTS
   FOREIGN KEY (ID)
   REFERENCES PRODUCTS(ID)
;

CREATE TABLE BUILDING_PRODUCTS_AUD (
  ID VARCHAR(36) NOT NULL,
  INDEX_VALUE DECIMAL(5,2),

  REV BIGINT NOT NULL,
  REVTYPE TINYINT,
  PRIMARY KEY (ID, REV)
);

ALTER TABLE BUILDING_PRODUCTS_AUD
   ADD CONSTRAINT BUILDING_PRODUCTS_AUD_REVINFO
   FOREIGN KEY (REV)
   REFERENCES REVINFO(REV)
;
