CREATE TABLE PRODUCTS
(
  ID VARCHAR(36),
  VERSION INT NOT NULL,
  FROM_ DATETIME(3) NOT NULL,
  TO_ DATETIME(3) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DISCOUNT DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS_AUD (
  ID VARCHAR(36) NOT NULL,
  VERSION INT,
  FROM_ DATETIME(3),
  TO_ DATETIME(3),
  DISCOUNT DECIMAL(3,1),
  NAME VARCHAR(50),

  REV BIGINT NOT NULL,
  REVTYPE TINYINT,
  PRIMARY KEY (ID, REV)
);

ALTER TABLE PRODUCTS_AUD
   ADD CONSTRAINT PRODUCTS_AUD_REVINFO
   FOREIGN KEY (REV)
   REFERENCES REVINFO(REV)
;

CREATE TABLE HOME_CONTENTS_PRODUCTS
(
  ID VARCHAR(36),
  TOTAL_INSURED_VALUE DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE HOME_CONTENTS_PRODUCTS
   ADD CONSTRAINT HOME_CONTENTS_PRODUCTS_PRODUCTS
   FOREIGN KEY (ID)
   REFERENCES PRODUCTS(ID)
;

CREATE TABLE HOME_CONTENTS_PRODUCTS_AUD (
  ID VARCHAR(36) NOT NULL,
  TOTAL_INSURED_VALUE DECIMAL(9,2),

  REV BIGINT NOT NULL,
  REVTYPE TINYINT,
  PRIMARY KEY (ID, REV)
);

ALTER TABLE HOME_CONTENTS_PRODUCTS_AUD
   ADD CONSTRAINT HOME_CONTENTS_PRODUCTS_AUD_REVINFO
   FOREIGN KEY (REV)
   REFERENCES REVINFO(REV)
;
