CREATE TABLE T_DISCOUNTS_SURCHARGES (
  ID             VARCHAR(36),
  CONTRACT_ID    VARCHAR(36)   NOT NULL,
  COMPONENT_ID   VARCHAR(36)   NOT NULL,
  DEFINITION_ID  VARCHAR(50)   NOT NULL,
  VALUE          DECIMAL(9,2)  NOT NULL,    -- value
  SYNC_TIMESTAMP BIGINT        NOT NULL,
  PRIMARY KEY(ID)
)
;

CREATE TABLE T_CONDITIONS (
  ID             VARCHAR(36),
  CONTRACT_ID    VARCHAR(36)   NOT NULL,
  COMPONENT_ID   VARCHAR(36)   NOT NULL,
  CONDITION_ID   VARCHAR(50)   NOT NULL,
  SYNC_TIMESTAMP BIGINT        NOT NULL,
  PRIMARY KEY(ID)
)
;

CREATE INDEX I_DISCOUNTS_SURCHARGES_CONTRACT_ID   ON T_DISCOUNTS_SURCHARGES (CONTRACT_ID);
CREATE INDEX I_DISCOUNTS_SURCHARGES_COMPONENT_ID  ON T_DISCOUNTS_SURCHARGES (COMPONENT_ID);
CREATE INDEX I_DISCOUNTS_SURCHARGES_SYNCTIMESTAMP ON T_DISCOUNTS_SURCHARGES (SYNC_TIMESTAMP);

CREATE INDEX I_CONDITIONS_CONTRACT_ID   ON T_CONDITIONS (CONTRACT_ID);
CREATE INDEX I_CONDITIONS_COMPONENT_ID  ON T_CONDITIONS (COMPONENT_ID);
CREATE INDEX I_CONDITIONS_SYNCTIMESTAMP ON T_CONDITIONS (SYNC_TIMESTAMP);
