CREATE TABLE T_CONTRACTS (
  ID            VARCHAR(36),
  PRODUCT       VARCHAR(36),
  STARTTIME     TIMESTAMP,
  ENDTIME       TIMESTAMP
)
;

CREATE TABLE T_BLOCKS (
  ID            VARCHAR(36),
  PARENT_ID     VARCHAR(36),
  CONTRACT_ID   VARCHAR(36),
  CONFIGURATION JSON
)
;